Create 2021-07-09-seminar-minutes-2021-04.md
wechaty/bot5.ml pull request #227
Opened 2021-08-01 02:48 UTC by IronConrad

is it OK？

2021-08-01 02:48 UTC, IronConrad commented
OK？

2021-08-01 15:53 UTC, lijiarui requested changes

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +  teaser: /assets/2021/seminar-03/group.jpg
We need image for this PR :)

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +3. 李佳芮， 句子互动创始人, **本次活动副主席**
副主席应该是另外一个同学~ 我是临时替换了一下~

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +- 副主席: Leo Song
主席是 Leo Song，副主席是段清华

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +![chair]({{ '/assets/2021/seminar-03/chair.jpg' | relative_url }})
我们需要这次活动的图片

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +
我们需要这次活动的图片

2021-08-01 15:53 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +![group]({{ '/assets/2021/seminar-03/group.jpg' | relative_url }})
我们需要这次活动的图片

2021-08-30 15:49 UTC, IronConrad commented
227

2021-08-30 15:51 UTC, IronConrad reviewed
fix text

2021-08-30 15:51 UTC, lijiarui commented
commit these image https://github.com/wechaty/bot5.ml/pull/228 to this PR.

2021-08-30 16:12 UTC, IronConrad reviewed
right photos

2021-08-30 16:16 UTC, lijiarui requested changes

2021-08-30 16:16 UTC, lijiarui commented on docs/assets/2021/seminar-04/a
> +
What is this file mean?

2021-08-30 16:16 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +author: conrad
Please add your profile md here.

2021-08-30 16:16 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +<iframe width="560" height="315" src="https://youtu.be/MuL-MzvqC-k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></
ping

2021-08-30 16:16 UTC, lijiarui commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +    src='{{ '/assets/js/viewer-js/#/assets/2021/seminar-04/luyuchao.pdf' | relative_url }}'
ping

2021-08-30 16:19 UTC, lijiarui commented
BTW， please accept my invitation to bot5 org by clicking https://github.com/wechaty

2021-08-30 16:58 UTC, IronConrad reviewed
i think fix all

2021-08-30 17:10 UTC, IronConrad reviewed
hope

2021-08-30 17:13 UTC, IronConrad commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +    src='{{ '/assets/js/viewer-js/#/assets/2021/seminar-04/luyuchao.pdf' | relative_url }}'
fix

2021-08-30 17:15 UTC, IronConrad commented on docs/_posts/2021-07-09-seminar-minutes-2021-04.md
> +    src='{{ '/assets/js/viewer-js/#/assets/2021/seminar-04/luyuchao.pdf' | relative_url }}'
upload

2021-08-30 17:16 UTC, IronConrad reviewed
last

2021-08-30 17:17 UTC, IronConrad reviewed
?

2021-08-31 04:53 UTC, lijiarui approved these changes
LGTM！

2021-08-31 04:53 UTC, merged